### ISSUE TITLE
Respect GOOGLE_CLOUD_PROJECT, not GCLOUD_PROJECT

### ISSUE THREAD

**Issue by aalexand** [GoogleCloudPlatform/cloud-profiler-nodejs#152]
GOOGLE_CLOUD_PROJECT is the environment variable we should use, I am pretty sure GCLOUD_PROJECT is deprecated / old. E.g. see https://cloud.google.com/appengine/docs/flexible/nodejs/runtime#environment_variables

**Comment by ofrobots** [comment]
Both the environment variables are documented in documentations of different products in various states. It is fine to support `GOOGLE_CLOUD_PROJECT`, but you should continue supporting `GCLOUD_PROJECT` as well.

**Comment by nolanmar511** [comment]
It looks like our code for this is redundant right now.
GCLOUD_PROJECT is  set at the projectId by `common.util.normalizeArguments()`, and https://github.com/googleapis/nodejs-common/issues/20 suggests also using GOOGLE_CLOUD_PROJECT. So, if that issue is resolved (and it may already be resolved; since one comment indicates google-auth-library uses GOOGLE_CLOUD_PROJECT), we wouldn't need to look at any environment variables for setting projectId.

**Comment by aalexand** [comment]
I verified (using Cloud Shell) that GOOGLE_CLOUD_PROJECT is already supported by the agent, apparently via the common library like mentioned in https://github.com/googleapis/nodejs-common/issues/20#issuecomment-371565829.
