### ISSUE TITLE
Make sure node version and agent version are available for backend analytics

### ISSUE THREAD

**Issue by nolanmar511** [GoogleCloudPlatform/cloud-profiler-nodejs#200]
We recently added language (#198) to deployment labels.
We should also consider adding the agent version and node version.

**Comment by nolanmar511** [comment]
Would we want there as separate labels, or part of the language label (particularly for node version)?

**Comment by ofrobots** [comment]
The user-agent header should already have some version information because we are using npm.im/@google-cloud/common – but not the version of this library – which would make sense to add as a label. I am not sure if the version of Node is also include in the user-agent header. If not, perhaps that should be a label too.

**Comment by aalexand** [comment]
These data are available in the stats.
